-- Task monitoring tables (runtime coordinated-task duplication detection + forensic episodes).
-- Delivered separately as a patch; run against the WSO2 coordination DB (same DB as oracle_cluster.sql).
-- Statements are terminated with "/" because TASK_DUPLICATION_EVENT uses a sequence + trigger for its ID.

CREATE TABLE RUNNING_TASK_OBSERVATION (
    NODE_ID VARCHAR2(512) NOT NULL,
    TASK_NAME VARCHAR2(512) NOT NULL,
    OBSERVED_AT NUMBER NOT NULL,
    PRIMARY KEY (NODE_ID, TASK_NAME)
)
/

CREATE TABLE TASK_DUPLICATION_EVENT (
    ID NUMBER NOT NULL,
    TASK_NAME VARCHAR2(512) NOT NULL,
    NODES VARCHAR2(1024) NOT NULL,
    DESTINED_NODE VARCHAR2(512),
    DETECTED_AT NUMBER NOT NULL,
    CLEARED_AT NUMBER,
    SEVERITY VARCHAR2(16),
    TASK_KIND VARCHAR2(16),
    PRIMARY KEY (ID)
)
/

CREATE SEQUENCE TASK_DUPLICATION_EVENT_SEQUENCE START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE OR REPLACE TRIGGER TASK_DUPLICATION_EVENT_TRIGGER
    BEFORE INSERT
    ON TASK_DUPLICATION_EVENT
    REFERENCING NEW AS NEW
    FOR EACH ROW
    BEGIN
        SELECT TASK_DUPLICATION_EVENT_SEQUENCE.nextval INTO :NEW.ID FROM dual;
    END;
/
