-- Task monitoring tables (runtime coordinated-task duplication detection + forensic episodes).
-- Delivered separately as a patch; run against the WSO2 coordination DB (same DB as mssql_cluster.sql).

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[RUNNING_TASK_OBSERVATION]') AND TYPE IN (N'U'))
CREATE TABLE RUNNING_TASK_OBSERVATION (
  NODE_ID VARCHAR (512) NOT NULL,
  TASK_NAME VARCHAR (512) NOT NULL,
  OBSERVED_AT BIGINT NOT NULL,
  PRIMARY KEY (NODE_ID, TASK_NAME)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TASK_DUPLICATION_EVENT]') AND TYPE IN (N'U'))
CREATE TABLE TASK_DUPLICATION_EVENT (
  ID BIGINT IDENTITY (1,1) NOT NULL,
  TASK_NAME VARCHAR (512) NOT NULL,
  NODES VARCHAR (1024) NOT NULL,
  DESTINED_NODE VARCHAR (512),
  DETECTED_AT BIGINT NOT NULL,
  CLEARED_AT BIGINT,
  SEVERITY VARCHAR (16),
  TASK_KIND VARCHAR (16),
  PRIMARY KEY (ID)
);
