-- Task monitoring tables (runtime coordinated-task duplication detection + forensic episodes).
-- Delivered separately as a patch; run against the WSO2 coordination DB (same DB as postgresql_cluster.sql).

CREATE TABLE IF NOT EXISTS RUNNING_TASK_OBSERVATION (
  NODE_ID VARCHAR (512) NOT NULL,
  TASK_NAME VARCHAR (512) NOT NULL,
  OBSERVED_AT BIGINT NOT NULL,
  PRIMARY KEY (NODE_ID, TASK_NAME)
);

CREATE SEQUENCE IF NOT EXISTS TASK_DUPLICATION_EVENT_PK_SEQ;
CREATE TABLE IF NOT EXISTS TASK_DUPLICATION_EVENT (
  ID BIGINT DEFAULT NEXTVAL('TASK_DUPLICATION_EVENT_PK_SEQ'),
  TASK_NAME VARCHAR (512) NOT NULL,
  NODES VARCHAR (1024) NOT NULL,
  DESTINED_NODE VARCHAR (512),
  DETECTED_AT BIGINT NOT NULL,
  CLEARED_AT BIGINT,
  SEVERITY VARCHAR (16),
  TASK_KIND VARCHAR (16),
  PRIMARY KEY (ID)
);
